# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20160325_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
